return {
	globals = {
		"script",
		"storage",
		"game",
		"data",
		"defines",
		"prototypes",
		"settings",
		"log",
		"math",
		"mods",
		"serpent",
		"helpers",
		"commands",
		"rendering",
		"feature_flags",
		"remote",

		"util",

		"apply_heat_pipe_glow",
		"pipecoverspictures",
		"reactor_circuit_wire_max_distance",
		"assembling_machine_circuit_wire_max_distance",
		"circuit_connector_definitions",
		"sound_variations",
		"volume_multiplier",
		"silo_cargo_hatch",
		"tile_variations_template",
		"tile_variations_template_with_transitions",
		"assembler3pipepictures",
		"water_tile_type_names",
		"water_transition_group_id",
		"lava_tile_type_names",
		"lava_transition_group_id",
		"out_of_map_transition_group_id",
		"out_of_map_tile_type_names",
		"default_transition_group_id",
		"default_circuit_wire_max_distance",
		"universal_connector_template",

		"PlanetsLib",
	},
	max_line_length = 1000,
}
