data:extend({

	{
		type = "double-setting",
		name = "planetary-distance-adjustments-nauvis-vulcanus-multiplier",
		setting_type = "startup",
		default_value = 1.15,
		minimum_value = 0.0001,
		maximum_value = 10000,
	},
	{
		type = "double-setting",
		name = "planetary-distance-adjustments-nauvis-gleba-multiplier",
		setting_type = "startup",
		default_value = 1,
		minimum_value = 0.0001,
		maximum_value = 10000,
	},
	{
		type = "double-setting",
		name = "planetary-distance-adjustments-nauvis-fulgora-multiplier",
		setting_type = "startup",
		default_value = 1,
		minimum_value = 0.0001,
		maximum_value = 10000,
	},
	{
		type = "double-setting",
		name = "planetary-distance-adjustments-vulcanus-gleba-multiplier",
		setting_type = "startup",
		default_value = 1,
		minimum_value = 0.0001,
		maximum_value = 10000,
	},
	{
		type = "double-setting",
		name = "planetary-distance-adjustments-gleba-fulgora-multiplier",
		setting_type = "startup",
		default_value = 1.66666667,
		minimum_value = 0.0001,
		maximum_value = 10000,
	},
	{
		type = "double-setting",
		name = "planetary-distance-adjustments-gleba-aquilo-multiplier",
		setting_type = "startup",
		default_value = 1,
		minimum_value = 0.0001,
		maximum_value = 10000,
	},
	{
		type = "double-setting",
		name = "planetary-distance-adjustments-fulgora-aquilo-multiplier",
		setting_type = "startup",
		default_value = 1.16666667,
		minimum_value = 0.0001,
		maximum_value = 10000,
	},
	{
		type = "double-setting",
		name = "planetary-distance-adjustments-aquilo-solar-system-edge-multiplier",
		setting_type = "startup",
		default_value = 1,
		minimum_value = 0.0001,
		maximum_value = 10000,
	},
	{
		type = "double-setting",
		name = "planetary-distance-adjustments-solar-system-edge-multiplier-shattered-planet",
		setting_type = "startup",
		default_value = 1,
		minimum_value = 0.0001,
		maximum_value = 10000,
	},
})
