data:extend({
	{
		type = "bool-setting",
		name = "rocs-hardcore-disable-lighted-electric-poles",
		setting_type = "startup",
		default_value = false,
	},
	{
		type = "bool-setting",
		name = "rocs-hardcore-a-enable-info-gui",
		setting_type = "runtime-per-user",
		default_value = true,
	},
	{
		type = "double-setting",
		name = "rocs-hardcore-biter-nighttime-bonus-damage-percent",
		setting_type = "runtime-global",
		default_value = 15,
		minimum_value = 0,
		maximum_value = 100,
	},
	{
		type = "double-setting",
		name = "rocs-hardcore-efficiency-module-effectiveness-multiplier",
		setting_type = "startup",
		default_value = 0.75,
		minimum_value = 0.0001,
		maximum_value = 10000,
	},
	{
		type = "bool-setting",
		name = "rocs-hardcore-expensive-utility-science",
		setting_type = "startup",
		default_value = true,
	},
	{
		type = "bool-setting",
		name = "rocs-hardcore-landmines-disabled",
		setting_type = "runtime-global",
		default_value = false,
	},
	{
		type = "double-setting",
		name = "rocs-hardcore-locomotive-fuel-spend-multiplier",
		setting_type = "startup",
		default_value = 3,
		minimum_value = 0.0001,
		maximum_value = 10000,
	},
	{
		type = "bool-setting",
		name = "rocs-hardcore-oresa-half-mixed-nauvis-ores",
		setting_type = "runtime-global",
		default_value = true,
	},
	{
		type = "bool-setting",
		name = "rocs-hardcore-oresb-fully-mixed-nauvis-ores",
		setting_type = "runtime-global",
		default_value = false,
	},
	{
		type = "double-setting",
		name = "rocs-hardcore-bonus-shotgun-damage-percent",
		setting_type = "startup",
		default_value = 40,
		minimum_value = 0,
		maximum_value = 10000,
	},
	{
		type = "double-setting",
		name = "rocs-hardcore-spacea-bonus-platform-foundation-tile-weight-percentage",
		setting_type = "startup",
		default_value = 10,
		minimum_value = 0,
		maximum_value = 10000,
	},
	{
		type = "int-setting",
		name = "rocs-hardcore-spacec-medium-asteroid-extra-physical-resistance",
		setting_type = "startup",
		default_value = 5,
		minimum_value = 0,
		maximum_value = 10000,
	},
	{
		type = "bool-setting",
		name = "rocs-hardcore-spaced-asteroids-early-copper-available",
		setting_type = "startup",
		default_value = true,
	},
})
