local item_sounds = require("__base__.prototypes.item_sounds")
local item_tints = require("__base__.prototypes.item-tints")

data:extend({
	{
		type = "item",
		name = "cargo-pod-nauvis",
		icon = "__Rocs-Hardcore-Cargo-Drops__/graphics/icons/cargo-pod-nauvis.png",
		subgroup = "cargo-pod",
		order = "a[cargo-pod-nauvis]",
		inventory_move_sound = item_sounds.metal_chest_inventory_move,
		pick_sound = item_sounds.metal_chest_inventory_pickup,
		drop_sound = item_sounds.metal_chest_inventory_move,
		stack_size = 20,
		weight = 1000 * 1000,
		random_tint_color = item_tints.iron_rust,
		default_import_location = "nauvis",
	},
	{
		type = "item",
		name = "cargo-pod-vulcanus",
		icon = "__Rocs-Hardcore-Cargo-Drops__/graphics/icons/cargo-pod-vulcanus.png",
		subgroup = "cargo-pod",
		order = "b[cargo-pod-vulcanus]",
		inventory_move_sound = item_sounds.metal_chest_inventory_move,
		pick_sound = item_sounds.metal_chest_inventory_pickup,
		drop_sound = item_sounds.metal_chest_inventory_move,
		stack_size = 20,
		weight = 1000 * 1000,
		random_tint_color = item_tints.iron_rust,
		default_import_location = "vulcanus",
	},
	{
		type = "item",
		name = "cargo-pod-fulgora",
		icon = "__Rocs-Hardcore-Cargo-Drops__/graphics/icons/cargo-pod-fulgora.png",
		subgroup = "cargo-pod",
		order = "c[cargo-pod-fulgora]",
		inventory_move_sound = item_sounds.metal_chest_inventory_move,
		pick_sound = item_sounds.metal_chest_inventory_pickup,
		drop_sound = item_sounds.metal_chest_inventory_move,
		stack_size = 20,
		weight = 1000 * 1000,
		random_tint_color = item_tints.iron_rust,
		default_import_location = "fulgora",
	},
	{
		type = "item",
		name = "cargo-pod-gleba",
		icon = "__Rocs-Hardcore-Cargo-Drops__/graphics/icons/cargo-pod-gleba.png",
		subgroup = "cargo-pod",
		order = "d[cargo-pod-gleba]",
		inventory_move_sound = item_sounds.metal_chest_inventory_move,
		pick_sound = item_sounds.metal_chest_inventory_pickup,
		drop_sound = item_sounds.metal_chest_inventory_move,
		stack_size = 20,
		weight = 1000 * 1000,
		random_tint_color = item_tints.organic_green,
		default_import_location = "gleba",
	},
	{
		type = "item",
		name = "cargo-pod-aquilo",
		icon = "__Rocs-Hardcore-Cargo-Drops__/graphics/icons/cargo-pod-aquilo.png",
		subgroup = "cargo-pod",
		order = "e[cargo-pod-aquilo]",
		inventory_move_sound = item_sounds.metal_chest_inventory_move,
		pick_sound = item_sounds.metal_chest_inventory_pickup,
		drop_sound = item_sounds.metal_chest_inventory_move,
		stack_size = 20,
		weight = 1000 * 1000,
		random_tint_color = item_tints.ice_blue,
	},
})
