data:extend({
	{
		type = "bool-setting",
		name = "no-underground-belts-on-platforms",
		setting_type = "startup",
		default_value = true,
		order = "a",
	},
	{
		type = "bool-setting",
		name = "no-underground-pipes-on-platforms",
		setting_type = "startup",
		default_value = true,
		order = "b",
	},
	{
		type = "double-setting",
		name = "rocs-hardcore-spacea-bonus-platform-foundation-tile-weight-percentage",
		setting_type = "startup",
		default_value = 10,
		minimum_value = 0,
		maximum_value = 10000,
		order = "c",
	},
	{
		type = "double-setting",
		name = "hard-space-connection-length-multiplier",
		setting_type = "startup",
		default_value = 1.5,
		minimum_value = 1,
		maximum_value = 10000,
		order = "d",
	},
	{
		type = "int-setting",
		name = "rocs-hardcore-spacec-medium-asteroid-extra-physical-resistance",
		setting_type = "startup",
		default_value = 5,
		minimum_value = 0,
		maximum_value = 10000,
		order = "e",
	},
	{
		type = "bool-setting",
		name = "rocs-hardcore-spaced-asteroids-early-copper-available",
		setting_type = "startup",
		default_value = true,
		order = "f",
	},
})
