-- data.raw["bool-setting"]["rocs-hardcore-gleba-cargo-drops-need-research"].default_value = false
-- data.raw["bool-setting"]["rocs-hardcore-fulgora-cargo-drops-need-research"].default_value = false
-- data.raw["bool-setting"]["rocs-hardcore-demolishers-cargo-drops-need-research"].default_value = false
